server:
  port: 9071 #9071  # utilize a porta "9" + api.id (numero da api). Tamanho de 4, complete com zero o número da api. 
#  use-forward-headers: true
  forward-headers-strategy: native
 
#------ API -------------------------------------------------------------------------------------------
api: 
  id: 71 #71 # Quando for para os ambientes de DEV/HOM/PROD informar o código da API registrado no sistema GCS.
  nome: '@project.name@'
  versao: '@project.version@'
  service-id: '@project.artifactId@'
       
info:
  api:
    id: ${api.id}
    ambiente: ${api.ambiente-publicacao}
    git: https://gitlab.correios.com.br/apis/sara/sara-atendimento.git
    
# -- Schedule -------------------------------------------------------------------------------------------    
schedule:
  sara-atendimento:
    execute: '0 0/2 * * * ?'  # a cada dois é executado
           
#------ Spring -------------------------------------------------------------------------------------------------------------- 
spring:
  application:
    name: '@project.artifactId@'
    
  profiles:
    active: local
    
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
      hibernate.jdbc.batch_size: 50
      hibernate.type: trace
      hibernate.use_sql_comments: true
      hibernate.showsql: true      
      hibernate.format_sql: true   

  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_NULL
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    joda-date-time-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-empty-json-arrays: false
    mapper:
      accept-case-insensitive-enums: true
      
    
#----------------------------------------------------------------------------------------------------------------------------------
# Assim como no Spring Boot 2, a maioria dos endpoints não são expostos via http por padrão, nós expomos todos eles. 
# Para PRODUCAO, você deve escolher cuidadosamente quais endpoints expor.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

 
    