api: 
  ambiente-publicacao: LOCAL
  password: sr89787hom
  
  client:
    url-email: https://jhom2.correiosnet.int/mensagens/v1/emails
    url-preco: https://apides.correios.com.br/preco
    url-idautorizacao-usuario: https://jhom2.correiosnet.int/idCorreiosWS-v1.2/idAutorizadorUsuario/idAutorizadorUsuarioService
  
#------ Spring -------------------------------------------------------------------------------------------
spring:         
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@scan-ac07.correiosnet.int:1521/ac07
    username: sarahom
    password: sr2005 
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
      hibernate.jdbc.batch_size: 50
      hibernate.type: trace
      hibernate.use_sql_comments: true
      hibernate.showsql: true      
      hibernate.format_sql: true   
    
  cloud:
    inetutils:
      preferred-networks:
      - eth0
    consul:
      enabled: false  # habilita para o uso do CONSUL local
      host: localhost
      port: 8500
      discovery: 
        instanceId: ${api.service-id}
        serviceName: ${api.service-id}
        prefer-ip-address: true 
        health-check-critical-timeout: 10m
                     
  redis:
    url: redis://localhost:6379
    
#    host: kuberneteshom.correios.com.br
#    port: 30845
#    password: ppmspwd
#    url: redis://localhost:6379
       
      
#------Logging --------------------------------------------------------------------------------------------------------------              
logging:
#  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    br.com.correios.api.sara-atendimento: DEBUG
    net.javacrumbs.shedlock: DEBUG
  file:
    name: sara-atendimento.log
    