server:
  port: 9091 #9091 
#  use-forward-headers: true
  forward-headers-strategy: native
 
#------ API -------------------------------------------------------------------------------------------
api: 
  id: 0 #71 # Quando for para os ambientes de DEV/HOM/PROD informar o código da API registrado no sistema GCS.
  nome: 'soccer'
  versao: '1.0.0'
  service-id: 'soccer'
       
info:
  api:
    id: ${api.id}
    ambiente: ${api.ambiente-publicacao}
    git: https://gitlab.correios.com.br/apis/sara/sara-atendimento.git
    
#------ Spring -------------------------------------------------------------------------------------------------------------- 
spring:
  application:
    name: 'soccer'
    
  profiles:
    active: local
    
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.jdbc.batch_size: 50
      hibernate.type: trace
      hibernate.use_sql_comments: true
      hibernate.showsql: true      
      hibernate.format_sql: true   

  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_NULL
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    joda-date-time-format: "yyyy-MM-dd'T'HH:mm:ss"
    serialization:
      write-empty-json-arrays: false
    mapper:
      accept-case-insensitive-enums: true
      
    
#----------------------------------------------------------------------------------------------------------------------------------
# Assim como no Spring Boot 2, a maioria dos endpoints não são expostos via http por padrão, nós expomos todos eles. 
# Para PRODUCAO, você deve escolher cuidadosamente quais endpoints expor.
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

 
    